services:

  postgres:
    image: 'postgres:16.4-alpine'
    command: postgres -c 'max_connections=200' # 기본 설정은 100 이나, 200까지 확장
    environment:
      - 'POSTGRES_DB=sample'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=sample'
    ports:
      - '54328:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - "63798:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
