create table if not exists tb_category
(
    id   bigint generated by default as identity
        primary key,
    code varchar(255),
    name varchar(255)
);

create table if not exists tb_rec_category
(
    id        bigint generated by default as identity primary key,
    parent_id bigint       not null,
    name      varchar(255) not null unique
);